from time import sleep
from random import choice
from random import randint
print(f'\33[1;34m{' Gerador de Senhas ':=^100}')
print('Este é um programa que te ajudará a criar uma senha forte!')
sleep(1)
print('Sua senha terá:')
sleep(1)
print('Uma letra maiúscula;')
sleep(1)
print('Letras minúsculas;')
sleep(1)
print('Um número;')
sleep(1)
print('Um símbolo.')
sleep(1)
print('Gerando senha')
sleep(1)
for e in range(0,5):
    print(' . ')
    sleep(1)
mai = ('A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z')
min = ('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z')
num = randint(0,9)
sim = ('!','@','#','$','%','&','*','-','_','+','=','?','^','~')
maif = choice(mai)
minf = choice(min)
numf = str(num)
simf = choice(sim)
print('Nossa sugestão para a sua senha é: ',end='')
print(maif,end='')
print(minf,end='')
print(numf,end='')
print(simf)