from time import sleep
from random import choice
print(f'\33[1;34m{' Gerador de Senhas ':=^100}')
print('Este é um programa que te ajudará a criar uma senha forte!')
sleep(1)
print('Sua senha terá:')
sleep(1)
print('Duas letras maiúsculas;')
sleep(1)
print('Duas letras minúsculas;')
sleep(1)
print('Dois números;')
sleep(1)
print('Dois símbolos.')
sleep(1)
print('Gerando senha')
sleep(1)
for e in range(0,5):
    print(' . ')
    sleep(1)
mai = ('A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z')
min = ('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z')
num = ('0','1','2','3','4','5','6','7','8','9')
sim = ('!','@','#','$','%','&','*','-','_','+','=','?')
print('Nossa sugestão para a sua senha é: ',end='')
for s in range(0,2):
    maif = choice(mai)
    minf = choice(min)
    numf = choice(num)
    simf = choice(sim)
    print(maif,end='')
    print(numf, end='')
    print(minf,end='')
    print(simf, end='')